{
    "comments": [
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "I think the fix is first qualifying paths before they are passed to the underlying FileSystem. I'm a bit surprised VFS doesn't do this already, but I guess it's worked so far since DFS (except for rename) just assumes it's the default FS when given an unqualified path.\n\nI think I'll qualify just for VFS#rename, but it could conceivably be done for all VFS calls.",
            "created": "2013-07-23T00:15:23.892+0000",
            "id": "13715898",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13715898",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-23T00:15:23.892+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "Sounds good.  It would be nice to have some kind of unit test for this as well.",
            "created": "2013-07-23T00:54:48.670+0000",
            "id": "13715938",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13715938",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-23T00:54:48.670+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "Had to think this one over a bit. FileSystem isn't like FileContext, in that given an unqualified path, it doesn't try to qualify it against the default FS first. It's supposed to just treat the path as one of its own.\r\n\r\nSo, simply move the cross-FS check in DFS#rename. Also tweak FileSystemLinkResolver to match.\r\n\r\nThe existing test cases weren't picking this up because the DFS returned from the minicluster use the minicluster conf, rather than the viewfs client's conf like in a real environment. So, I make sure to set the DFS defaultFS to the viewfs. I tested \"fail before/works after\" with the testcase and tested with the shell.\r\n\r\nAlso took the opportunity to correct some javadoc in DFS.",
            "created": "2013-07-24T06:20:05.398+0000",
            "id": "13718031",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13718031",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-24T06:20:05.398+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "{code}\n    // Assumes path belongs to this FileSystem.\n    // Callers are responsible for checking this\n    FileSystem fs = filesys;\n{code}\n\nI don't see where you are actually checking that the path belongs to the FileSystem in most of the callers.\n\nFor example, back before symlinks support in FileSystem, code like this:\n{code}\nFileSystem fs = FileSystem.get(hdfs...);\nfs.open(\"file:///boguspath\");\n{code}\n\nWould generate a stacktrace like this:\n{code}\nException in thread \"main\" java.lang.IllegalArgumentException: Wrong FS: file:/boguspath, expected: hdfs://localhost:6000\n        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:590)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:170)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:246)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:79)\n        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:711)\n{code}\n\nAfter the symlinks support, it generated this:\n{code}\nException in thread \"main\" java.lang.IllegalArgumentException: Wrong FS: file:/tmp/t, expected: hdfs://localhost:6000\n        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:636)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:181)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:91)\n        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:290)\n        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:286)\n        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:78)\n        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:286)\n        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:757)\n{code}\n\nIt seems like this change would simply pass the incorrect path through to the FileSystem, which seems wrong.\n\ntreating unqualified (i.e., \"schemeless\") Paths as owned by the current FileSystem should not require disabling the checks for Paths which *do* have a wrong scheme.",
            "created": "2013-07-24T22:52:55.119+0000",
            "id": "13718969",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13718969",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-24T22:52:55.119+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "They're checked in DistributedFileSystem#getPathName by calling FileSystem#checkPath (which does the validation you posted). All of our paths in DFS go through getPathName (or at least are supposed to).",
            "created": "2013-07-24T23:04:14.228+0000",
            "id": "13718991",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13718991",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-24T23:04:14.228+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "I'm not sure why Jenkins didn't run on this, but I re-submitted it.",
            "created": "2013-07-26T17:24:44.446+0000",
            "id": "13720969",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13720969",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-26T17:24:44.446+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "resubmit because jenkins did not run the first time\r\n",
            "created": "2013-07-29T21:36:38.611+0000",
            "id": "13723007",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13723007",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-29T21:36:38.611+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "body": "{color:red}-1 overall{color}.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12594798/hadoop-9761-1.patch\n  against trunk revision .\n\n    {color:green}+1 @author{color}.  The patch does not contain any @author tags.\n\n    {color:green}+1 tests included{color}.  The patch appears to include 1 new or modified test files.\n\n    {color:green}+1 javac{color}.  The applied patch does not increase the total number of javac compiler warnings.\n\n    {color:green}+1 javadoc{color}.  The javadoc tool did not generate any warning messages.\n\n    {color:green}+1 eclipse:eclipse{color}.  The patch built with eclipse:eclipse.\n\n    {color:green}+1 findbugs{color}.  The patch does not introduce any new Findbugs (version 1.3.9) warnings.\n\n    {color:green}+1 release audit{color}.  The applied patch does not increase the total number of release audit warnings.\n\n    {color:red}-1 core tests{color}.  The patch failed these unit tests in hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs:\n\n                  org.apache.hadoop.hdfs.TestDFSShell\n\n    {color:green}+1 contrib tests{color}.  The patch passed contrib unit tests.\n\nTest results: https://builds.apache.org/job/PreCommit-HADOOP-Build/2869//testReport/\nConsole output: https://builds.apache.org/job/PreCommit-HADOOP-Build/2869//console\n\nThis message is automatically generated.",
            "created": "2013-07-30T00:05:57.861+0000",
            "id": "13723173",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13723173",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "updated": "2013-07-30T00:05:57.861+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "I believe the test failure is related to the HADOOP-9652 build breakage that we had, not this patch.  Basically a stray println was causing the regular expressions in TestDFSShell to fail.\n",
            "created": "2013-07-30T01:25:23.467+0000",
            "id": "13723243",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13723243",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-30T01:25:23.467+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "I'm re-uploading this to get a clean Jenkins run.  I added a newline to CHANGES.txt in the mapreduce and yarn directories, so that we can get a full jenkins run on this before committing.",
            "created": "2013-07-30T01:26:18.516+0000",
            "id": "13723245",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13723245",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-30T01:26:18.516+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "body": "{color:green}+1 overall{color}.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12594836/HADOOP-9761_viewfilesystem_rename_fails.003.patch\n  against trunk revision .\n\n    {color:green}+1 @author{color}.  The patch does not contain any @author tags.\n\n    {color:green}+1 tests included{color}.  The patch appears to include 1 new or modified test files.\n\n    {color:green}+1 javac{color}.  The applied patch does not increase the total number of javac compiler warnings.\n\n    {color:green}+1 javadoc{color}.  The javadoc tool did not generate any warning messages.\n\n    {color:green}+1 eclipse:eclipse{color}.  The patch built with eclipse:eclipse.\n\n    {color:green}+1 findbugs{color}.  The patch does not introduce any new Findbugs (version 1.3.9) warnings.\n\n    {color:green}+1 release audit{color}.  The applied patch does not increase the total number of release audit warnings.\n\n    {color:green}+1 core tests{color}.  The patch passed unit tests in hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs.\n\n    {color:green}+1 contrib tests{color}.  The patch passed contrib unit tests.\n\nTest results: https://builds.apache.org/job/PreCommit-HADOOP-Build/2875//testReport/\nConsole output: https://builds.apache.org/job/PreCommit-HADOOP-Build/2875//console\n\nThis message is automatically generated.",
            "created": "2013-07-30T03:47:04.869+0000",
            "id": "13723363",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13723363",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "updated": "2013-07-30T03:47:04.869+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "still didn't get an MR unit test run last time.  Let's try again.",
            "created": "2013-07-30T17:22:30.868+0000",
            "id": "13724102",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13724102",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-30T17:22:30.868+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "body": "{color:red}-1 overall{color}.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12594990/0001-HADOOP-9761.004.patch\n  against trunk revision .\n\n    {color:green}+1 @author{color}.  The patch does not contain any @author tags.\n\n    {color:green}+1 tests included{color}.  The patch appears to include 1 new or modified test files.\n\n    {color:green}+1 javac{color}.  The applied patch does not increase the total number of javac compiler warnings.\n\n    {color:green}+1 javadoc{color}.  The javadoc tool did not generate any warning messages.\n\n    {color:green}+1 eclipse:eclipse{color}.  The patch built with eclipse:eclipse.\n\n    {color:green}+1 findbugs{color}.  The patch does not introduce any new Findbugs (version 1.3.9) warnings.\n\n    {color:green}+1 release audit{color}.  The applied patch does not increase the total number of release audit warnings.\n\n    {color:red}-1 core tests{color}.  The patch failed these unit tests in hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client:\n\n                  org.apache.hadoop.yarn.client.api.impl.TestNMClient\n\n    {color:green}+1 contrib tests{color}.  The patch passed contrib unit tests.\n\nTest results: https://builds.apache.org/job/PreCommit-HADOOP-Build/2885//testReport/\nConsole output: https://builds.apache.org/job/PreCommit-HADOOP-Build/2885//console\n\nThis message is automatically generated.",
            "created": "2013-07-30T19:48:02.555+0000",
            "id": "13724318",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13724318",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "updated": "2013-07-30T19:48:02.555+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "Thanks for the poking around, Colin. I ran the failed test successfully locally, so I'm guessing it's a flake in YARN.\n\nI think we should commit the earlier patch without the whitespace changes as it also does have a jenkins +1, unless there are further review comments.",
            "created": "2013-07-31T03:38:22.931+0000",
            "id": "13724817",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13724817",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-31T03:38:22.931+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "{code}\n+    // Assumes path belongs to this FileSystem.\n+    // Callers are responsible for checking this\n+    FileSystem fs = filesys;\n{code}\n\nThanks for the explanation about this.  Can we add a comment like \"this is validated in {{FileSystem#checkPath}}\"?\n\n{code}\n+          if (fs.getUri() != getUri()) {\n+            throw new IOException(\"Renames across FileSystems not supported\");\n+          }\n{code}\n\nWe should be using {{equals}} here, not {{!=}}.\n\n+1 once those are addressed.",
            "created": "2013-07-31T17:28:53.179+0000",
            "id": "13725460",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725460",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-31T17:28:53.179+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "Rolled up your suggested changes, thanks, On revisiting this though, I went a bit further:\r\n\r\n* Removed the same check from  {{rename(Path, Path, Options)}} that I missed before\r\n* Removed throwing the rename across FileSystems IOException at all, since this is handled already in FileSystem#checkPath, and symlink tests in fact check for that {{IllegalArgumentException}}.",
            "created": "2013-07-31T20:45:58.120+0000",
            "id": "13725700",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725700",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-31T20:45:58.120+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "OK, good.  So basically this boils down to removing unnecessary checks that were hampering {{ViewFileSystem}}-- that were already being done in {{getPathName}}, etc.\n\n{code}\n         public Void next(final FileSystem fs, final Path p)\n             throws IOException {\n-          // Since we know it's this DFS for both, can just call doCall again\n+          // Should just throw an error in FileSystem#checkPath\n           return doCall(p);\n         }\n{code}\n\nI think the comment should be something more like \"if the new path is in a different filesystem, doCall will throw an exception.\"  \"Should just throw an error\" implies that it always fails, which definitely isn't true... if the symlink is to something on the same FS.",
            "created": "2013-07-31T22:19:48.834+0000",
            "id": "13725784",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725784",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-07-31T22:19:48.834+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "So the way {{FileSystemLinkResolver#resolve}} works, it calls {{#doCall}} if the symlink points to within the same FileSystem, and goes out to {{#next}} if it's a different FileSystem. So, I think this means the {{#doCall}} here should always fail the {{FileSystem#checkPath}} check. This is a bit confusing compared to {{FSLinkResolver}}, since {{#next}} is being used differently.",
            "created": "2013-07-31T22:28:36.932+0000",
            "id": "13725789",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725789",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-07-31T22:28:36.932+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "body": "{color:green}+1 overall{color}.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12595272/hadoop-9761-2.patch\n  against trunk revision .\n\n    {color:green}+1 @author{color}.  The patch does not contain any @author tags.\n\n    {color:green}+1 tests included{color}.  The patch appears to include 1 new or modified test files.\n\n    {color:green}+1 javac{color}.  The applied patch does not increase the total number of javac compiler warnings.\n\n    {color:green}+1 javadoc{color}.  The javadoc tool did not generate any warning messages.\n\n    {color:green}+1 eclipse:eclipse{color}.  The patch built with eclipse:eclipse.\n\n    {color:green}+1 findbugs{color}.  The patch does not introduce any new Findbugs (version 1.3.9) warnings.\n\n    {color:green}+1 release audit{color}.  The applied patch does not increase the total number of release audit warnings.\n\n    {color:green}+1 core tests{color}.  The patch passed unit tests in hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs.\n\n    {color:green}+1 contrib tests{color}.  The patch passed contrib unit tests.\n\nTest results: https://builds.apache.org/job/PreCommit-HADOOP-Build/2897//testReport/\nConsole output: https://builds.apache.org/job/PreCommit-HADOOP-Build/2897//console\n\nThis message is automatically generated.",
            "created": "2013-07-31T23:07:19.793+0000",
            "id": "13725811",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725811",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393"
                },
                "displayName": "Hadoop QA",
                "emailAddress": "jira@apache.org",
                "name": "hadoopqa",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa"
            },
            "updated": "2013-07-31T23:07:19.793+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "Yeah, you're absolutely right.  There is a difference between {{FileSystemLinkResolver}}, where you have this code in {{FileSystemLinkResolver#resolve}}:\n\n{code}\n        // Have to call next if it's a new FS\n        if (!fs.equals(filesys)) {\n          return next(fs, p);\n        }\n{code}\n\nand {{FSLinkResolver#resolve}}, where you have this code:\n{code}\n    // Loop until all symlinks are resolved or the limit is reached\n    for (boolean isLink = true; isLink;) {\n      try {\n        in = next(fs, p);\n        isLink = false;\n      ...\n{code}\n\nIn other words, FSLinkResolver doesn't have {{doCall}}, only {{next}}.\n\nbq. So, I think this means the #doCall here should always fail the FileSystem#checkPath check.\n\nI think it's better to just raise an exception directly, than to rely on another method to do it.  There's less coupling in the code and it's clearer.  Maybe something like this?\n{code}\n         public Void next(final FileSystem fs, final Path p)\n             throws IOException {\n           throw new IllegalArgumentException(\"Wrong FS: \"+path+\n                                       \", expected: \"+ fileSys.getUri());\n         }\n{code}\n\nI think this makes it a lot more obvious what's going on... what do you think",
            "created": "2013-08-01T01:24:03.445+0000",
            "id": "13725942",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13725942",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-08-01T01:24:03.445+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "body": "I had that thought, it's a tradeoff between clarity and duplicating the exception. I was hoping that having a comment would alleviate the clarity concern, but I can re-rev if you want.\n\nIt's also perhaps worth noting that duplication is across sub-projects, i.e. {{FileSystem#checkPath}} is in Common while DFS is in HDFS.",
            "created": "2013-08-01T23:50:59.330+0000",
            "id": "13727103",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13727103",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Andrew Wang",
                "emailAddress": "andrew.wang@cloudera.com",
                "name": "andrew.wang",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=andrew.wang"
            },
            "updated": "2013-08-01T23:50:59.330+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "OK.  That is a fair point.  Duplicating the exception could be a maintenance issue.\n\n+1",
            "created": "2013-08-02T17:19:43.901+0000",
            "id": "13727823",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13727823",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-08-02T17:19:43.901+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "body": "commited in 2.3",
            "created": "2013-08-02T21:48:11.444+0000",
            "id": "13728167",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13728167",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Colin Patrick McCabe",
                "emailAddress": "cmccabe@cloudera.com",
                "name": "cmccabe",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=cmccabe"
            },
            "updated": "2013-08-02T21:48:11.444+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "body": "SUCCESS: Integrated in Hadoop-trunk-Commit #4206 (See [https://builds.apache.org/job/Hadoop-trunk-Commit/4206/])\nHADOOP-9761.  ViewFileSystem#rename fails when using DistributedFileSystem (Andrew Wang via Colin Patrick McCabe) (cmccabe: http://svn.apache.org/viewcvs.cgi/?root=Apache-SVN&view=rev&rev=1509874)\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/CHANGES.txt\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystemLinkResolver.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemHdfs.java\n",
            "created": "2013-08-02T22:32:44.143+0000",
            "id": "13728208",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13728208",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "updated": "2013-08-02T22:32:44.143+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "body": "SUCCESS: Integrated in Hadoop-Yarn-trunk #290 (See [https://builds.apache.org/job/Hadoop-Yarn-trunk/290/])\nHADOOP-9761.  ViewFileSystem#rename fails when using DistributedFileSystem (Andrew Wang via Colin Patrick McCabe) (cmccabe: http://svn.apache.org/viewcvs.cgi/?root=Apache-SVN&view=rev&rev=1509874)\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/CHANGES.txt\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystemLinkResolver.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemHdfs.java\n",
            "created": "2013-08-03T10:55:39.698+0000",
            "id": "13728511",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13728511",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "updated": "2013-08-03T10:55:39.698+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "body": "FAILURE: Integrated in Hadoop-Hdfs-trunk #1480 (See [https://builds.apache.org/job/Hadoop-Hdfs-trunk/1480/])\nHADOOP-9761.  ViewFileSystem#rename fails when using DistributedFileSystem (Andrew Wang via Colin Patrick McCabe) (cmccabe: http://svn.apache.org/viewcvs.cgi/?root=Apache-SVN&view=rev&rev=1509874)\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/CHANGES.txt\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystemLinkResolver.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemHdfs.java\n",
            "created": "2013-08-03T13:19:20.879+0000",
            "id": "13728535",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13728535",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "updated": "2013-08-03T13:19:20.879+0000"
        },
        {
            "author": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "body": "SUCCESS: Integrated in Hadoop-Mapreduce-trunk #1507 (See [https://builds.apache.org/job/Hadoop-Mapreduce-trunk/1507/])\nHADOOP-9761.  ViewFileSystem#rename fails when using DistributedFileSystem (Andrew Wang via Colin Patrick McCabe) (cmccabe: http://svn.apache.org/viewcvs.cgi/?root=Apache-SVN&view=rev&rev=1509874)\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/CHANGES.txt\n* /hadoop/common/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystemLinkResolver.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java\n* /hadoop/common/trunk/hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemHdfs.java\n",
            "created": "2013-08-03T14:10:40.794+0000",
            "id": "13728544",
            "self": "https://issues.apache.org/jira/rest/api/2/issue/12659221/comment/13728544",
            "updateAuthor": {
                "active": true,
                "avatarUrls": {
                    "16x16": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                    "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
                },
                "displayName": "Hudson",
                "emailAddress": "jira@apache.org",
                "name": "hudson",
                "self": "https://issues.apache.org/jira/rest/api/2/user?username=hudson"
            },
            "updated": "2013-08-03T14:10:40.794+0000"
        }
    ],
    "maxResults": 27,
    "startAt": 0,
    "total": 27
}
